### PR TITLE
textures for steel items.

### PR DESCRIPTION
**Pull request by XavierDD1st**

### CODE REVIEW

**Comment by Fexcraft** [comment]
`"layer0": "fvm:items/steel_ingotmaterial_steel_ingot"`
this doesn't seem right 0.o

shouldn't it be `"layer0": "fvm:items/steel_ingot"`?

**Comment by XavierDD1st** [comment]
yeah it should.

**Comment by Fexcraft** [comment]
also the plate too...

**Comment by XavierDD1st** [comment]
fixed

**Pull request merged**
